package TicTacToe;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Box.java
//  @ Date : 25.11.2012
//  @ Author :
//
//
public class Box {

	private boolean occupied;
	public Marker mark = new Marker();

	private Boolean occupied() {
	   return occupied;
	}
    public void setMarker(Marker mark) {
        this.mark = mark;
    }
	public int getMarker() {
	    return mark.Marker;
	}

	public boolean place(Marker x) {
	    if (!(occupied)) {
            mark = x;
            occupied = true;
            return occupied;
        }
        return false;
	}
}
