//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Box.java
//  @ Date : 25.11.2012
//  @ Author :
//
//
public class Box {

	public boolean occupied;
	public Marker mark;
	public Marker = 1;

	public Boolean occupied() {
	   return mark;
	}
	
	public Marker getMarker() {
	
	}
	
	public void place(Object Marker) {
	
	}
}
