//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : GaUI.java
//  @ Date : 25.11.2012
//  @ Author : 
//
//




public class GaUI {
 public void drawMarker( Box X) {
 
 }
 
 public void drawFrame() {
 
 }
 
 public void resetFrame() {
 
 }
 
 public void mouseListener() {
 
 }
}
