//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Marker.java
//  @ Date : 25.11.2012
//  @ Author : 
//
//

public class Marker {
    public int Marker; //marker is either 0(empty),1(player1) or 2(player2)

}
