//
//
<<<<<<< HEAD
//  Generated by StarUML(tm) Java Add-In
=======
//  Generated StarUML(tm) Java Add-In
>>>>>>> master1
//
//  @ Project : Untitled
//  @ File Name : TicTacToe.java
//  @ Date : 25.11.2012
//  @ Author :
    //jawdljaklwdjklawjdkljawdklajwkldjawldkjawkldjawkldjawkldjawkldjawkldawdjawkldjawlkdj

public final class TicTacToe {
 public Box Board[9] = new Box[];
 public int NrOfGames;
 
 public void playTicTacToe() {
 
 }
 
 public void createPlayers() {
 
 }
 
 public int checkWin() {
 
 }
 
 public Player switchPl() {
 
 }
 
 public void main() {
 
 }
}
